import "./globals.css";
import { Roboto } from "next/font/google";

// components
import Nav from "./auth/Nav";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Next Fullstack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} mx-4 md:mx-48 xl:mx-96 bg-gray-200 text-gray-800`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
